# Generated by Django 4.1.7 on 2023-02-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bussiness_name',
            field=models.CharField(default='my bussiness', max_length=100),
        ),
    ]
